"""initial schemas, access roles and tables (POC-06)

Creates three schemas with enforced access boundaries:
- fv_inference (NOLOGIN group): reads food_catalog, writes run telemetry,
  and has NO privileges at all on benchmark (hidden reference labels).
- fv_evaluator (NOLOGIN group): reads everything, writes benchmark.
Login users are created per environment and granted one of these groups
(see README); no passwords live in migrations. Roles are cluster-level and
are intentionally left in place on downgrade.

Revision ID: 0001
Revises:
Create Date: 2026-10-02 21:27:46.143984
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


SCHEMAS = ("food_catalog", "telemetry", "benchmark")
INFERENCE_WRITABLE = (
    "telemetry.images",
    "telemetry.runs",
    "telemetry.stage_events",
    "telemetry.attempt_events",
    "telemetry.permitted_results",
    "telemetry.corrections",
)

GRANTS = f"""
REVOKE ALL ON SCHEMA {", ".join(SCHEMAS)} FROM PUBLIC;

GRANT USAGE ON SCHEMA food_catalog, telemetry TO fv_inference;
GRANT SELECT ON ALL TABLES IN SCHEMA food_catalog TO fv_inference;
GRANT SELECT, INSERT, UPDATE ON {", ".join(INFERENCE_WRITABLE)} TO fv_inference;
GRANT SELECT, INSERT ON telemetry.configurations TO fv_inference;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA telemetry TO fv_inference;
-- Deliberately nothing on schema benchmark for fv_inference.

GRANT USAGE ON SCHEMA food_catalog, telemetry, benchmark TO fv_evaluator;
GRANT SELECT ON ALL TABLES IN SCHEMA food_catalog, telemetry TO fv_evaluator;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA benchmark TO fv_evaluator;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA benchmark TO fv_evaluator;
"""


def upgrade() -> None:
    for role in ("fv_inference", "fv_evaluator"):
        op.execute(
            f"DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') "
            f"THEN CREATE ROLE {role} NOLOGIN; END IF; END $$;"
        )
    for schema in SCHEMAS:
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calibration_versions",
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("fitting_split", sa.Text(), nullable=False),
        sa.Column("success_definition", sa.Text(), nullable=False),
        sa.Column("bin_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("uncertainty", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fitting_split <> 'test'", name=op.f("ck_calibration_versions_not_test_split")
        ),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_calibration_versions")),
        schema="benchmark",
    )
    op.create_table(
        "food_records",
        sa.Column("food_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_food_id", sa.Text(), nullable=False),
        sa.Column("source_version", sa.Text(), nullable=False),
        sa.Column("data_type", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("preparation", sa.Text(), nullable=True),
        sa.Column("brand", sa.Text(), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("basis_kind", sa.Text(), nullable=False),
        sa.Column("basis_quantity", sa.Numeric(), nullable=False),
        sa.Column("basis_unit", sa.Text(), nullable=False),
        sa.Column("density_g_per_ml", sa.Numeric(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(basis_kind <> 'per_100g' OR (basis_quantity = 100 AND basis_unit = 'g')) AND "
            "(basis_kind <> 'per_100ml' OR (basis_quantity = 100 AND basis_unit = 'ml'))",
            name=op.f("ck_food_records_basis_consistent"),
        ),
        sa.CheckConstraint(
            "basis_kind IN ('per_100g', 'per_100ml', 'per_serving')",
            name=op.f("ck_food_records_basis_kind"),
        ),
        sa.CheckConstraint("basis_unit IN ('g', 'ml')", name=op.f("ck_food_records_basis_unit")),
        sa.CheckConstraint(
            "basis_quantity > 0", name=op.f("ck_food_records_basis_quantity_positive")
        ),
        sa.CheckConstraint(
            "density_g_per_ml IS NULL OR density_g_per_ml > 0",
            name=op.f("ck_food_records_density_positive"),
        ),
        sa.PrimaryKeyConstraint("food_id", name=op.f("pk_food_records")),
        sa.UniqueConstraint(
            "provider",
            "provider_food_id",
            "source_version",
            name=op.f("uq_food_records_provider_provider_food_id_source_version"),
        ),
        schema="food_catalog",
    )
    op.create_table(
        "configurations",
        sa.Column("config_id", sa.Text(), nullable=False),
        sa.Column("pipeline_id", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("data_version", sa.Text(), nullable=True),
        sa.Column("preprocessing_version", sa.Text(), nullable=True),
        sa.Column("git_commit", sa.String(length=40), nullable=True),
        sa.Column("locked", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("config_id", name=op.f("pk_configurations")),
        schema="telemetry",
    )
    op.create_table(
        "images",
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("original_sha256", sa.String(length=64), nullable=False),
        sa.Column("processed_sha256", sa.String(length=64), nullable=True),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("consent_basis", sa.Text(), nullable=False),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("consent_basis <> ''", name=op.f("ck_images_consent_required")),
        sa.PrimaryKeyConstraint("image_id", name=op.f("pk_images")),
        sa.UniqueConstraint("object_key", name=op.f("uq_images_object_key")),
        schema="telemetry",
    )
    op.create_table(
        "samples",
        sa.Column("sample_id", sa.Text(), nullable=False),
        sa.Column("image_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("split", sa.Text(), nullable=False),
        sa.Column("reference_version", sa.Text(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "split IN ('development', 'calibration', 'test')", name=op.f("ck_samples_split")
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["telemetry.images.image_id"],
            name=op.f("fk_samples_image_id_images"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("sample_id", name=op.f("pk_samples")),
        schema="benchmark",
    )
    op.create_index(
        op.f("ix_samples_group_id"), "samples", ["group_id"], unique=False, schema="benchmark"
    )
    op.create_table(
        "food_nutrients",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("food_id", sa.BigInteger(), nullable=False),
        sa.Column("nutrient", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "amount IS NULL OR amount >= 0", name=op.f("ck_food_nutrients_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["food_catalog.food_records.food_id"],
            name=op.f("fk_food_nutrients_food_id_food_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_food_nutrients")),
        sa.UniqueConstraint("food_id", "nutrient", name=op.f("uq_food_nutrients_food_id_nutrient")),
        schema="food_catalog",
    )
    op.create_table(
        "food_portions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("food_id", sa.BigInteger(), nullable=False),
        sa.Column("portion_name", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=True),
        sa.Column("gram_weight", sa.Numeric(), nullable=False),
        sa.CheckConstraint("gram_weight > 0", name=op.f("ck_food_portions_gram_weight_positive")),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["food_catalog.food_records.food_id"],
            name=op.f("fk_food_portions_food_id_food_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_food_portions")),
        sa.UniqueConstraint(
            "food_id", "portion_name", name=op.f("uq_food_portions_food_id_portion_name")
        ),
        schema="food_catalog",
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("pipeline_id", sa.Text(), nullable=False),
        sa.Column("config_id", sa.Text(), nullable=True),
        sa.Column("image_id", sa.UUID(), nullable=True),
        sa.Column("batch_id", sa.Text(), nullable=True),
        sa.Column("sample_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("is_mock", sa.Boolean(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_total_ms", sa.Float(), nullable=False),
        sa.Column("logical_requests", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("model_calls", sa.Integer(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("timeouts", sa.Integer(), nullable=False),
        sa.Column("blocked_attempts", sa.Integer(), nullable=False),
        sa.Column("known_cost_usd", sa.Numeric(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Numeric(), nullable=True),
        sa.CheckConstraint(
            "status IN ('complete', 'partial', 'abstained', 'failed')", name=op.f("ck_runs_status")
        ),
        sa.CheckConstraint("finished_at >= started_at", name=op.f("ck_runs_time_order")),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["telemetry.configurations.config_id"],
            name=op.f("fk_runs_config_id_configurations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["telemetry.images.image_id"],
            name=op.f("fk_runs_image_id_images"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_runs")),
        schema="telemetry",
    )
    op.create_index(
        op.f("ix_runs_batch_id"), "runs", ["batch_id"], unique=False, schema="telemetry"
    )
    op.create_index(
        op.f("ix_runs_sample_id"), "runs", ["sample_id"], unique=False, schema="telemetry"
    )
    op.create_table(
        "evaluation_metrics",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("reference_version", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["telemetry.runs.run_id"],
            name=op.f("fk_evaluation_metrics_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_metrics")),
        sa.UniqueConstraint(
            "run_id",
            "reference_version",
            "metric",
            name=op.f("uq_evaluation_metrics_run_id_reference_version_metric"),
        ),
        schema="benchmark",
    )
    op.create_index(
        op.f("ix_evaluation_metrics_run_id"),
        "evaluation_metrics",
        ["run_id"],
        unique=False,
        schema="benchmark",
    )
    op.create_table(
        "reference_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sample_id", sa.Text(), nullable=False),
        sa.Column("verified_identity", sa.Text(), nullable=False),
        sa.Column("preparation", sa.Text(), nullable=True),
        sa.Column("edible_grams", sa.Numeric(), nullable=False),
        sa.Column("reference_source", sa.Text(), nullable=False),
        sa.Column("reviewer", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "edible_grams > 0", name=op.f("ck_reference_items_edible_grams_positive")
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["benchmark.samples.sample_id"],
            name=op.f("fk_reference_items_sample_id_samples"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_items")),
        schema="benchmark",
    )
    op.create_index(
        op.f("ix_reference_items_sample_id"),
        "reference_items",
        ["sample_id"],
        unique=False,
        schema="benchmark",
    )
    op.create_table(
        "reference_nutrients",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sample_id", sa.Text(), nullable=False),
        sa.Column("nutrient", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=True),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("quality_grade", sa.String(length=1), nullable=False),
        sa.CheckConstraint(
            "quality_grade IN ('A', 'B', 'C')", name=op.f("ck_reference_nutrients_quality_grade")
        ),
        sa.CheckConstraint(
            "amount IS NULL OR amount >= 0", name=op.f("ck_reference_nutrients_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["benchmark.samples.sample_id"],
            name=op.f("fk_reference_nutrients_sample_id_samples"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_nutrients")),
        sa.UniqueConstraint(
            "sample_id", "nutrient", name=op.f("uq_reference_nutrients_sample_id_nutrient")
        ),
        schema="benchmark",
    )
    op.create_table(
        "attempt_events",
        sa.Column("attempt_id", sa.Text(), nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("span_id", sa.Text(), nullable=True),
        sa.Column("logical_request_id", sa.Text(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("operation", sa.Text(), nullable=False),
        sa.Column("is_model_call", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("timeout_s", sa.Float(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("http_status_class", sa.Text(), nullable=True),
        sa.Column("retry_reason", sa.Text(), nullable=True),
        sa.Column("retry_after_s", sa.Float(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("provider_model", sa.Text(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(), nullable=True),
        sa.Column("cost_provenance", sa.Text(), nullable=False),
        sa.Column("price_table_version", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["telemetry.runs.run_id"],
            name=op.f("fk_attempt_events_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("attempt_id", name=op.f("pk_attempt_events")),
        sa.UniqueConstraint(
            "logical_request_id",
            "attempt_number",
            name=op.f("uq_attempt_events_logical_request_id_attempt_number"),
        ),
        schema="telemetry",
    )
    op.create_index(
        op.f("ix_attempt_events_run_id"),
        "attempt_events",
        ["run_id"],
        unique=False,
        schema="telemetry",
    )
    op.create_table(
        "corrections",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("field", sa.Text(), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["telemetry.runs.run_id"],
            name=op.f("fk_corrections_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corrections")),
        schema="telemetry",
    )
    op.create_index(
        op.f("ix_corrections_run_id"), "corrections", ["run_id"], unique=False, schema="telemetry"
    )
    op.create_table(
        "permitted_results",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.Text(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dropped_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["telemetry.runs.run_id"],
            name=op.f("fk_permitted_results_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_permitted_results")),
        schema="telemetry",
    )
    op.create_table(
        "stage_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("span_id", sa.Text(), nullable=False),
        sa.Column("parent_span_id", sa.Text(), nullable=True),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("cache_state", sa.Text(), nullable=False),
        sa.CheckConstraint("duration_ms >= 0", name=op.f("ck_stage_events_duration_non_negative")),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["telemetry.runs.run_id"],
            name=op.f("fk_stage_events_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_events")),
        sa.UniqueConstraint("run_id", "span_id", name=op.f("uq_stage_events_run_id_span_id")),
        schema="telemetry",
    )
    op.create_index(
        op.f("ix_stage_events_run_id"), "stage_events", ["run_id"], unique=False, schema="telemetry"
    )
    # ### end Alembic commands ###
    op.execute(GRANTS)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stage_events_run_id"), table_name="stage_events", schema="telemetry")
    op.drop_table("stage_events", schema="telemetry")
    op.drop_table("permitted_results", schema="telemetry")
    op.drop_index(op.f("ix_corrections_run_id"), table_name="corrections", schema="telemetry")
    op.drop_table("corrections", schema="telemetry")
    op.drop_index(op.f("ix_attempt_events_run_id"), table_name="attempt_events", schema="telemetry")
    op.drop_table("attempt_events", schema="telemetry")
    op.drop_table("reference_nutrients", schema="benchmark")
    op.drop_index(
        op.f("ix_reference_items_sample_id"), table_name="reference_items", schema="benchmark"
    )
    op.drop_table("reference_items", schema="benchmark")
    op.drop_index(
        op.f("ix_evaluation_metrics_run_id"), table_name="evaluation_metrics", schema="benchmark"
    )
    op.drop_table("evaluation_metrics", schema="benchmark")
    op.drop_index(op.f("ix_runs_sample_id"), table_name="runs", schema="telemetry")
    op.drop_index(op.f("ix_runs_batch_id"), table_name="runs", schema="telemetry")
    op.drop_table("runs", schema="telemetry")
    op.drop_table("food_portions", schema="food_catalog")
    op.drop_table("food_nutrients", schema="food_catalog")
    op.drop_index(op.f("ix_samples_group_id"), table_name="samples", schema="benchmark")
    op.drop_table("samples", schema="benchmark")
    op.drop_table("images", schema="telemetry")
    op.drop_table("configurations", schema="telemetry")
    op.drop_table("food_records", schema="food_catalog")
    op.drop_table("calibration_versions", schema="benchmark")
    # ### end Alembic commands ###
    for schema in reversed(SCHEMAS):
        op.execute(f"DROP SCHEMA IF EXISTS {schema}")
