"""catalog retrieval metadata and full-text search (POC-07)

Adds FDC nutrient identifiers, portion units/modifiers, food category, parsed
preparation state, publication/retrieval metadata, and a generated English
tsvector with a GIN index for lexical retrieval (no embeddings).

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 21:39:21.848943
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "food_nutrients",
        sa.Column("source_nutrient_id", sa.Integer(), nullable=True),
        schema="food_catalog",
    )
    op.add_column(
        "food_nutrients",
        sa.Column("source_nutrient_name", sa.Text(), nullable=True),
        schema="food_catalog",
    )
    op.add_column(
        "food_portions", sa.Column("measure_unit", sa.Text(), nullable=True), schema="food_catalog"
    )
    op.add_column(
        "food_portions", sa.Column("modifier", sa.Text(), nullable=True), schema="food_catalog"
    )
    op.add_column(
        "food_portions",
        sa.Column("portion_source", sa.Text(), server_default="source_data", nullable=False),
        schema="food_catalog",
    )
    op.add_column(
        "food_records", sa.Column("category", sa.Text(), nullable=True), schema="food_catalog"
    )
    op.add_column(
        "food_records",
        sa.Column("preparation_state", sa.Text(), server_default="not_stated", nullable=False),
        schema="food_catalog",
    )
    op.add_column(
        "food_records", sa.Column("published_date", sa.Date(), nullable=True), schema="food_catalog"
    )
    op.add_column(
        "food_records",
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        schema="food_catalog",
    )
    op.add_column(
        "food_records",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(name, '') || ' ' || coalesce(category, '') "
                "|| ' ' || coalesce(brand, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
        schema="food_catalog",
    )
    op.create_index(
        "ix_food_records_search_vector",
        "food_records",
        ["search_vector"],
        unique=False,
        schema="food_catalog",
        postgresql_using="gin",
    )
    op.create_check_constraint(
        op.f("ck_food_records_preparation_state"),
        "food_records",
        "preparation_state IN ('uncooked', 'cooked', 'not_stated', 'ambiguous')",
        schema="food_catalog",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_food_records_preparation_state"), "food_records", schema="food_catalog"
    )
    op.drop_index(
        "ix_food_records_search_vector",
        table_name="food_records",
        schema="food_catalog",
        postgresql_using="gin",
    )
    op.drop_column("food_records", "search_vector", schema="food_catalog")
    op.drop_column("food_records", "retrieved_at", schema="food_catalog")
    op.drop_column("food_records", "published_date", schema="food_catalog")
    op.drop_column("food_records", "preparation_state", schema="food_catalog")
    op.drop_column("food_records", "category", schema="food_catalog")
    op.drop_column("food_portions", "portion_source", schema="food_catalog")
    op.drop_column("food_portions", "modifier", schema="food_catalog")
    op.drop_column("food_portions", "measure_unit", schema="food_catalog")
    op.drop_column("food_nutrients", "source_nutrient_name", schema="food_catalog")
    op.drop_column("food_nutrients", "source_nutrient_id", schema="food_catalog")
    # ### end Alembic commands ###
